package com.myverbatm.verbatm.backend.models;

import com.google.appengine.api.datastore.Entity;
import com.googlecode.objectify.annotation.Id;

import java.util.Date;

/**
 * Information about the POV needed to display in the feed
 */
@com.googlecode.objectify.annotation.Entity
public class POVInfo implements Comparable<POVInfo> {

    /**
     * Unique identifier of this POV Entity in the database.
     */
    private Long id;

    /**
     * VerbatmUser given title for the POV
     */
    private String title;

    /**
     * Date the POV was published
     */
    private Date datePublished;

    /**
     * Number of up votes this POV has received
     */
    private Long numUpVotes;

    /**
     * POV's creator's user key
     */
    private Long creatorUserId;

    public POVInfo() {

    }

    /**
     * Creates a POVInfo instance from an Entity containing each property
     * (probably generated by a Projection Query)
     * @param entity
     */
    public POVInfo(Entity entity) {
        this.id = entity.getKey().getId();
        this.title = (String) entity.getProperty("title");
        this.datePublished = (Date) entity.getProperty("datePublished");
        this.numUpVotes = (Long) entity.getProperty("numUpVotes");
        this.creatorUserId = (Long) entity.getProperty("creatorUserId");
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getDatePublished() {
        return datePublished;
    }

    public void setDatePublished(Date datePublished) {
        this.datePublished = datePublished;
    }

    public Long getNumUpVotes() {
        return numUpVotes;
    }

    public void setNumUpVotes(Long numUpVotes) {
        this.numUpVotes = numUpVotes;
    }

    public Long getCreatorUserId() {
        return creatorUserId;
    }

    public void setCreatorUserId(Long creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * Sorts pov infos so that the one with more votes is less
     * @param other
     * @return
     */
    @Override
    public int compareTo(POVInfo other) {
        return (int) (other.numUpVotes - this.numUpVotes);
    }
}
