source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'PromiseKit'
pod 'Fabric'
pod 'Crashlytics'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'FBSDKCoreKit' 
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

link_with 'Verbatm'