source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'PromiseKit'
pod 'Fabric'
pod 'Crashlytics'
pod 'Parse'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod "FBSDKMessengerShareKit"
pod 'ParseFacebookUtilsV4'
pod 'Branch'

link_with 'Verbatm'