source 'https://github.com/CocoaPods/Specs.git'
pod 'Google/Analytics', '~> 1.0.0'
use_frameworks!
pod 'PromiseKit'
pod 'Fabric'
pod 'Crashlytics'
pod 'Digits'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Optimizely-iOS-SDK'

link_with 'Verbatm'