/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryVerbatmApp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryVerbatmApp (29 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLVerbatmAppImage;
@class GTLVerbatmAppPage;
@class GTLVerbatmAppVerbatmUser;
@class GTLVerbatmAppVideo;

@interface GTLQueryVerbatmApp : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, assign) NSInteger channelId;
@property (nonatomic, assign) NSInteger count;
@property (nonatomic, copy) NSString *email;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) BOOL liked;
@property (nonatomic, assign) long long pageId;
@property (nonatomic, assign) long long postId;
@property (nonatomic, copy) NSString *shareType;
@property (nonatomic, assign) long long userId;

#pragma mark - "image" methods
// These create a GTLQueryVerbatmApp object.

// Method: verbatmApp.image.getImage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppImage.
+ (instancetype)queryForImageGetImageWithIdentifier:(long long)identifier;

// Method: verbatmApp.image.getUploadURI
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppUploadURI.
+ (instancetype)queryForImageGetUploadURI;

// Method: verbatmApp.image.insertImage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppImage.
+ (instancetype)queryForImageInsertImageWithObject:(GTLVerbatmAppImage *)object;

// Method: verbatmApp.image.removeImage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForImageRemoveImageWithIdentifier:(long long)identifier;

// Method: verbatmApp.image.updateImage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppImage.
+ (instancetype)queryForImageUpdateImageWithObject:(GTLVerbatmAppImage *)object;

#pragma mark - "page" methods
// These create a GTLQueryVerbatmApp object.

// Method: verbatmApp.page.getPage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPage.
+ (instancetype)queryForPageGetPageWithIdentifier:(long long)identifier;

// Method: verbatmApp.page.insertPage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPage.
+ (instancetype)queryForPageInsertPageWithObject:(GTLVerbatmAppPage *)object;

// Method: verbatmApp.page.removePage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForPageRemovePageWithIdentifier:(long long)identifier;

// Method: verbatmApp.page.updatePage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPage.
+ (instancetype)queryForPageUpdatePageWithObject:(GTLVerbatmAppPage *)object;

#pragma mark - "post" methods
// These create a GTLQueryVerbatmApp object.

// Method: verbatmApp.post.getImagesInPage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppImageCollection.
+ (instancetype)queryForPostGetImagesInPageWithPageId:(long long)pageId;

// Method: verbatmApp.post.getPagesInPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPageCollection.
+ (instancetype)queryForPostGetPagesInPostWithPostId:(long long)postId;

// Method: verbatmApp.post.getPostsInChannel
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPostCollection.
+ (instancetype)queryForPostGetPostsInChannelWithChannelId:(NSInteger)channelId;

// Method: verbatmApp.post.getRecentPosts
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPostCollection.
+ (instancetype)queryForPostGetRecentPostsWithCount:(NSInteger)count;

// Method: verbatmApp.post.getUsersWhoLikePost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUserCollection.
+ (instancetype)queryForPostGetUsersWhoLikePostWithPostId:(long long)postId;

// Method: verbatmApp.post.getUsersWhoSharedPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUserCollection.
+ (instancetype)queryForPostGetUsersWhoSharedPostWithPostId:(long long)postId;

// Method: verbatmApp.post.getVideosInPage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVideoCollection.
+ (instancetype)queryForPostGetVideosInPageWithPageId:(long long)pageId;

// Method: verbatmApp.post.insertPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForPostInsertPost;

// Method: verbatmApp.post.userLikedPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForPostUserLikedPostWithLiked:(BOOL)liked
                                            postId:(long long)postId
                                            userId:(long long)userId;

// Method: verbatmApp.post.userSharedPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForPostUserSharedPostWithPostId:(long long)postId
                                           shareType:(NSString *)shareType
                                              userId:(long long)userId;

#pragma mark - "verbatmuser" methods
// These create a GTLQueryVerbatmApp object.

// Method: verbatmApp.verbatmuser.getUser
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUser.
+ (instancetype)queryForVerbatmuserGetUserWithIdentifier:(long long)identifier;

// Method: verbatmApp.verbatmuser.getUserFromEmail
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUser.
+ (instancetype)queryForVerbatmuserGetUserFromEmailWithEmail:(NSString *)email;

// Method: verbatmApp.verbatmuser.insertUser
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUser.
+ (instancetype)queryForVerbatmuserInsertUserWithObject:(GTLVerbatmAppVerbatmUser *)object;

// Method: verbatmApp.verbatmuser.removeUser
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForVerbatmuserRemoveUserWithIdentifier:(long long)identifier;

// Method: verbatmApp.verbatmuser.updateUser
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUser.
+ (instancetype)queryForVerbatmuserUpdateUserWithObject:(GTLVerbatmAppVerbatmUser *)object;

#pragma mark - "video" methods
// These create a GTLQueryVerbatmApp object.

// Method: verbatmApp.video.getUploadURI
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppUploadURI.
+ (instancetype)queryForVideoGetUploadURI;

// Method: verbatmApp.video.getVideo
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVideo.
+ (instancetype)queryForVideoGetVideoWithIdentifier:(long long)identifier;

// Method: verbatmApp.video.insertVideo
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVideo.
+ (instancetype)queryForVideoInsertVideoWithObject:(GTLVerbatmAppVideo *)object;

// Method: verbatmApp.video.removeVideo
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForVideoRemoveVideoWithIdentifier:(long long)identifier;

// Method: verbatmApp.video.updateVideo
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVideo.
+ (instancetype)queryForVideoUpdateVideoWithObject:(GTLVerbatmAppVideo *)object;

@end
