/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryVerbatmApp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryVerbatmApp (16 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLVerbatmAppChannel;
@class GTLVerbatmAppPost;
@class GTLVerbatmAppVerbatmUser;

@interface GTLQueryVerbatmApp : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, assign) NSInteger channelId;
@property (nonatomic, assign) NSInteger count;
@property (nonatomic, copy) NSString *email;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) BOOL liked;
@property (nonatomic, assign) NSInteger pageId;
@property (nonatomic, assign) NSInteger postId;
@property (nonatomic, copy) NSString *shareType;
@property (nonatomic, assign) NSInteger userId;

#pragma mark - "channel" methods
// These create a GTLQueryVerbatmApp object.

// Method: verbatmApp.channel.insertChannel
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppChannel.
+ (instancetype)queryForChannelInsertChannelWithObject:(GTLVerbatmAppChannel *)object;

#pragma mark - "post" methods
// These create a GTLQueryVerbatmApp object.

// Method: verbatmApp.post.getImagesInPage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppImageCollection.
+ (instancetype)queryForPostGetImagesInPageWithPageId:(NSInteger)pageId;

// Method: verbatmApp.post.getPagesInPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPageCollection.
+ (instancetype)queryForPostGetPagesInPostWithPostId:(NSInteger)postId;

// Method: verbatmApp.post.getPostsInChannel
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPostCollection.
+ (instancetype)queryForPostGetPostsInChannelWithChannelId:(NSInteger)channelId;

// Method: verbatmApp.post.getRecentPosts
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPostCollection.
+ (instancetype)queryForPostGetRecentPostsWithCount:(NSInteger)count;

// Method: verbatmApp.post.getUsersWhoLikePost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUserCollection.
+ (instancetype)queryForPostGetUsersWhoLikePostWithPostId:(NSInteger)postId;

// Method: verbatmApp.post.getUsersWhoSharedPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUserCollection.
+ (instancetype)queryForPostGetUsersWhoSharedPostWithPostId:(NSInteger)postId;

// Method: verbatmApp.post.getVideosInPage
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVideoCollection.
+ (instancetype)queryForPostGetVideosInPageWithPageId:(NSInteger)pageId;

// Method: verbatmApp.post.insertPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppPost.
+ (instancetype)queryForPostInsertPostWithObject:(GTLVerbatmAppPost *)object;

// Method: verbatmApp.post.userLikedPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForPostUserLikedPostWithLiked:(BOOL)liked
                                            postId:(NSInteger)postId
                                            userId:(NSInteger)userId;

// Method: verbatmApp.post.userSharedPost
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForPostUserSharedPostWithPostId:(NSInteger)postId
                                           shareType:(NSString *)shareType
                                              userId:(NSInteger)userId;

#pragma mark - "verbatmuser" methods
// These create a GTLQueryVerbatmApp object.

// Method: verbatmApp.verbatmuser.getUser
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUser.
+ (instancetype)queryForVerbatmuserGetUserWithIdentifier:(long long)identifier;

// Method: verbatmApp.verbatmuser.getUserFromEmail
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUser.
+ (instancetype)queryForVerbatmuserGetUserFromEmailWithEmail:(NSString *)email;

// Method: verbatmApp.verbatmuser.insertUser
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUser.
+ (instancetype)queryForVerbatmuserInsertUserWithObject:(GTLVerbatmAppVerbatmUser *)object;

// Method: verbatmApp.verbatmuser.removeUser
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
+ (instancetype)queryForVerbatmuserRemoveUserWithIdentifier:(long long)identifier;

// Method: verbatmApp.verbatmuser.updateUser
//  Authorization scope(s):
//   kGTLAuthScopeVerbatmAppUserinfoEmail
// Fetches a GTLVerbatmAppVerbatmUser.
+ (instancetype)queryForVerbatmuserUpdateUserWithObject:(GTLVerbatmAppVerbatmUser *)object;

@end
