/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppPost.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPost (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVerbatmAppImageListWrapper;
@class GTLVerbatmAppPageListWrapper;
@class GTLVerbatmAppTimestamp;
@class GTLVerbatmAppVideoListWrapper;

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPost
//

@interface GTLVerbatmAppPost : GTLObject
@property (nonatomic, retain) NSNumber *channelId;  // intValue
@property (nonatomic, retain) GTLVerbatmAppTimestamp *dateCreated;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // intValue

@property (nonatomic, retain) GTLVerbatmAppImageListWrapper *images;
@property (nonatomic, retain) GTLVerbatmAppPageListWrapper *pages;
@property (nonatomic, retain) NSNumber *sharedFromPostId;  // intValue
@property (nonatomic, retain) GTLVerbatmAppVideoListWrapper *videos;
@end
