/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API

#import "GTLVerbatmAppConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeVerbatmAppUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
