/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmApp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API

#import "GTLVerbatmAppConstants.h"

#import "GTLVerbatmAppImage.h"
#import "GTLVerbatmAppImageCollection.h"
#import "GTLVerbatmAppImageListWrapper.h"
#import "GTLVerbatmAppPage.h"
#import "GTLVerbatmAppPageCollection.h"
#import "GTLVerbatmAppPageListWrapper.h"
#import "GTLVerbatmAppPost.h"
#import "GTLVerbatmAppPostCollection.h"
#import "GTLVerbatmAppTimestamp.h"
#import "GTLVerbatmAppVerbatmUser.h"
#import "GTLVerbatmAppVerbatmUserCollection.h"
#import "GTLVerbatmAppVideo.h"
#import "GTLVerbatmAppVideoCollection.h"
#import "GTLVerbatmAppVideoListWrapper.h"

#import "GTLQueryVerbatmApp.h"
#import "GTLServiceVerbatmApp.h"
