/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppVideoListWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppVideoListWrapper (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppVideoListWrapper.h"

#import "GTLVerbatmAppVideo.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppVideoListWrapper
//

@implementation GTLVerbatmAppVideoListWrapper
@dynamic videos;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"videos" : [GTLVerbatmAppVideo class]
  };
  return map;
}

@end
