/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppTimestamp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppTimestamp (0 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppTimestamp
//

@interface GTLVerbatmAppTimestamp : GTLObject
@property (nonatomic, retain) NSNumber *date;  // intValue
@property (nonatomic, retain) NSNumber *day;  // intValue
@property (nonatomic, retain) NSNumber *hours;  // intValue
@property (nonatomic, retain) NSNumber *minutes;  // intValue
@property (nonatomic, retain) NSNumber *month;  // intValue
@property (nonatomic, retain) NSNumber *nanos;  // intValue
@property (nonatomic, retain) NSNumber *seconds;  // intValue
@property (nonatomic, retain) NSNumber *time;  // longLongValue
@property (nonatomic, retain) NSNumber *timezoneOffset;  // intValue
@property (nonatomic, retain) NSNumber *year;  // intValue
@end
