/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppPOVInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPOVInfo (0 custom class methods, 5 custom properties)

#import "GTLVerbatmAppPOVInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPOVInfo
//

@implementation GTLVerbatmAppPOVInfo
@dynamic creatorUserId, datePublished, identifier, numUpVotes, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
