/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPage (0 custom class methods, 4 custom properties)

#import "GTLVerbatmAppPage.h"

#import "GTLVerbatmAppImage.h"
#import "GTLVerbatmAppVideo.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPage
//

@implementation GTLVerbatmAppPage
@dynamic images, key, text, videos;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"images" : [GTLVerbatmAppImage class],
    @"videos" : [GTLVerbatmAppVideo class]
  };
  return map;
}

@end
