/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmApp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API

#import "GTLVerbatmAppConstants.h"

#import "GTLVerbatmAppEmail.h"
#import "GTLVerbatmAppImage.h"
#import "GTLVerbatmAppPage.h"
#import "GTLVerbatmAppPageCollection.h"
#import "GTLVerbatmAppPhoneNumber.h"
#import "GTLVerbatmAppPOV.h"
#import "GTLVerbatmAppPOVInfo.h"
#import "GTLVerbatmAppResultsWithCursor.h"
#import "GTLVerbatmAppVerbatmUser.h"
#import "GTLVerbatmAppVideo.h"

#import "GTLQueryVerbatmApp.h"
#import "GTLServiceVerbatmApp.h"
