/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppImage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppImage (0 custom class methods, 6 custom properties)

#import "GTLVerbatmAppImage.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppImage
//

@implementation GTLVerbatmAppImage
@dynamic identifier, indexInPage, pageNum, servingUrl, text, textYPosition;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
