/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPOVCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPOVCollection (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppPOVCollection.h"

#import "GTLVerbatmAppPOV.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPOVCollection
//

@implementation GTLVerbatmAppPOVCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLVerbatmAppPOV class]
  };
  return map;
}

@end
