/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppPostCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPostCollection (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppPostCollection.h"

#import "GTLVerbatmAppPost.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPostCollection
//

@implementation GTLVerbatmAppPostCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLVerbatmAppPost class]
  };
  return map;
}

@end
