/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppResultsWithCursor.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppResultsWithCursor (0 custom class methods, 2 custom properties)

#import "GTLVerbatmAppResultsWithCursor.h"

#import "GTLVerbatmAppList.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppResultsWithCursor
//

@implementation GTLVerbatmAppResultsWithCursor
@dynamic cursorString, results;
@end
