/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPageCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPageCollection (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppPageCollection.h"

#import "GTLVerbatmAppPage.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPageCollection
//

@implementation GTLVerbatmAppPageCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLVerbatmAppPage class]
  };
  return map;
}

@end
