/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppChannel.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppChannel (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVerbatmAppTimestamp;

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppChannel
//

@interface GTLVerbatmAppChannel : GTLObject
@property (nonatomic, retain) NSNumber *creatorUserId;  // intValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // intValue

@property (nonatomic, copy) NSString *name;
@property (nonatomic, retain) GTLVerbatmAppTimestamp *ts;
@end
