/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppTimestamp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppTimestamp (0 custom class methods, 10 custom properties)

#import "GTLVerbatmAppTimestamp.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppTimestamp
//

@implementation GTLVerbatmAppTimestamp
@dynamic date, day, hours, minutes, month, nanos, seconds, time, timezoneOffset,
         year;
@end
