/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPOV.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPOV (0 custom class methods, 7 custom properties)

#import "GTLVerbatmAppPOV.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPOV
//

@implementation GTLVerbatmAppPOV
@dynamic creatorUserId, datePublished, identifier, numUpVotes, pageIds, title,
         usersWhoHaveLikedIDs;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"pageIds" : [NSNumber class],
    @"usersWhoHaveLikedIDs" : [NSNumber class]
  };
  return map;
}

@end
