/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPage (0 custom class methods, 4 custom properties)

#import "GTLVerbatmAppPage.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPage
//

@implementation GTLVerbatmAppPage
@dynamic identifier, imageIds, indexInPOV, videoIds;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"imageIds" : [NSNumber class],
    @"videoIds" : [NSNumber class]
  };
  return map;
}

@end
