/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPhoneNumber.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPhoneNumber (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppPhoneNumber.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPhoneNumber
//

@implementation GTLVerbatmAppPhoneNumber
@dynamic number;
@end
