/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppPost.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPost (0 custom class methods, 4 custom properties)

#import "GTLVerbatmAppPost.h"

#import "GTLVerbatmAppTimestamp.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPost
//

@implementation GTLVerbatmAppPost
@dynamic channelId, dateCreated, identifier, sharedFromPostId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
