/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppVerbatmUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppVerbatmUser (0 custom class methods, 5 custom properties)

#import "GTLVerbatmAppVerbatmUser.h"

#import "GTLVerbatmAppEmail.h"
#import "GTLVerbatmAppImage.h"
#import "GTLVerbatmAppPhoneNumber.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppVerbatmUser
//

@implementation GTLVerbatmAppVerbatmUser
@dynamic email, key, name, phoneNumber, profilePhoto;
@end
