/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppImageListWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppImageListWrapper (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppImageListWrapper.h"

#import "GTLVerbatmAppImage.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppImageListWrapper
//

@implementation GTLVerbatmAppImageListWrapper
@dynamic images;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"images" : [GTLVerbatmAppImage class]
  };
  return map;
}

@end
