/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPageListWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPageListWrapper (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppPageListWrapper.h"

#import "GTLVerbatmAppPage.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPageListWrapper
//

@implementation GTLVerbatmAppPageListWrapper
@dynamic pages;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"pages" : [GTLVerbatmAppPage class]
  };
  return map;
}

@end
