/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppPost.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPost (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVerbatmAppTimestamp;

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPost
//

@interface GTLVerbatmAppPost : GTLObject
@property (nonatomic, retain) NSNumber *channelId;  // longLongValue
@property (nonatomic, retain) GTLVerbatmAppTimestamp *dateCreated;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) NSNumber *sharedFromPostId;  // longLongValue
@end
