/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppVerbatmUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppVerbatmUser (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVerbatmAppEmail;
@class GTLVerbatmAppImage;
@class GTLVerbatmAppPhoneNumber;

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppVerbatmUser
//

@interface GTLVerbatmAppVerbatmUser : GTLObject
@property (nonatomic, retain) GTLVerbatmAppEmail *email;
@property (nonatomic, retain) NSNumber *key;  // longLongValue
@property (nonatomic, copy) NSString *name;
@property (nonatomic, retain) GTLVerbatmAppPhoneNumber *phoneNumber;
@property (nonatomic, retain) GTLVerbatmAppImage *profilePhoto;
@end
