/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPOV.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPOV (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVerbatmAppPage;

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPOV
//

@interface GTLVerbatmAppPOV : GTLObject
@property (nonatomic, retain) NSNumber *creatorUserKey;  // longLongValue
@property (nonatomic, retain) GTLDateTime *datePublished;
@property (nonatomic, retain) NSNumber *key;  // longLongValue
@property (nonatomic, retain) NSArray *pages;  // of GTLVerbatmAppPage
@property (nonatomic, copy) NSString *title;
@property (nonatomic, retain) NSArray *whats;  // of NSString
@property (nonatomic, copy) NSString *where;
@end
