/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmApp_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API

#import "GTLVerbatmAppConstants.m"

#import "GTLVerbatmAppEmail.m"
#import "GTLVerbatmAppImage.m"
#import "GTLVerbatmAppPage.m"
#import "GTLVerbatmAppPageCollection.m"
#import "GTLVerbatmAppPhoneNumber.m"
#import "GTLVerbatmAppPOV.m"
#import "GTLVerbatmAppPOVInfo.m"
#import "GTLVerbatmAppResultsWithCursor.m"
#import "GTLVerbatmAppVerbatmUser.m"
#import "GTLVerbatmAppVideo.m"

#import "GTLQueryVerbatmApp.m"
#import "GTLServiceVerbatmApp.m"
