/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmApp_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API

#import "GTLVerbatmAppConstants.m"

#import "GTLVerbatmAppImage.m"
#import "GTLVerbatmAppImageCollection.m"
#import "GTLVerbatmAppPage.m"
#import "GTLVerbatmAppPageCollection.m"
#import "GTLVerbatmAppPost.m"
#import "GTLVerbatmAppPostCollection.m"
#import "GTLVerbatmAppTimestamp.m"
#import "GTLVerbatmAppUploadURI.m"
#import "GTLVerbatmAppVerbatmUser.m"
#import "GTLVerbatmAppVerbatmUserCollection.m"
#import "GTLVerbatmAppVideo.m"
#import "GTLVerbatmAppVideoCollection.m"

#import "GTLQueryVerbatmApp.m"
#import "GTLServiceVerbatmApp.m"
