/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPOV.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPOV (0 custom class methods, 7 custom properties)

#import "GTLVerbatmAppPOV.h"

#import "GTLVerbatmAppPage.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPOV
//

@implementation GTLVerbatmAppPOV
@dynamic creatorUserKey, datePublished, key, pages, title, whats, where;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"pages" : [GTLVerbatmAppPage class],
    @"whats" : [NSString class]
  };
  return map;
}

@end
