/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppVideo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppVideo (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppVideo.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppVideo
//

@implementation GTLVerbatmAppVideo
@dynamic key;
@end
