/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppImage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppImage (0 custom class methods, 4 custom properties)

#import "GTLVerbatmAppImage.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppImage
//

@implementation GTLVerbatmAppImage
@dynamic key, servingUrl, text, userKey;
@end
