/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppChannel.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppChannel (0 custom class methods, 4 custom properties)

#import "GTLVerbatmAppChannel.h"

#import "GTLVerbatmAppTimestamp.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppChannel
//

@implementation GTLVerbatmAppChannel
@dynamic creatorUserId, identifier, name, ts;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
