/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppVideo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppVideo (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppVideo
//

@interface GTLVerbatmAppVideo : GTLObject
@property (nonatomic, retain) NSNumber *key;  // longLongValue
@property (nonatomic, copy) NSString *servingUrl;
@property (nonatomic, copy) NSString *text;
@property (nonatomic, retain) NSNumber *userKey;  // longLongValue
@end
