/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPOVInfo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPOVInfo (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPOVInfo
//

@interface GTLVerbatmAppPOVInfo : GTLObject
@property (nonatomic, copy) NSString *coverPicUrl;
@property (nonatomic, retain) NSNumber *creatorUserId;  // longLongValue
@property (nonatomic, retain) GTLDateTime *datePublished;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) NSNumber *numUpVotes;  // longLongValue
@property (nonatomic, copy) NSString *title;
@end
