/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppVerbatmUserCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppVerbatmUserCollection (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppVerbatmUserCollection.h"

#import "GTLVerbatmAppVerbatmUser.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppVerbatmUserCollection
//

@implementation GTLVerbatmAppVerbatmUserCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLVerbatmAppVerbatmUser class]
  };
  return map;
}

@end
