/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppUploadURI.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppUploadURI (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppUploadURI.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppUploadURI
//

@implementation GTLVerbatmAppUploadURI
@dynamic uploadURIString;
@end
