/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppVideoCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppVideoCollection (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppVideoCollection.h"

#import "GTLVerbatmAppVideo.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppVideoCollection
//

@implementation GTLVerbatmAppVideoCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLVerbatmAppVideo class]
  };
  return map;
}

@end
