/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppVerbatmUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppVerbatmUser (0 custom class methods, 6 custom properties)

#import "GTLVerbatmAppVerbatmUser.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppVerbatmUser
//

@implementation GTLVerbatmAppVerbatmUser
@dynamic email, identifier, likedPOVIDs, name, phoneNumber, profilePhotoImageID;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"likedPOVIDs" : [NSNumber class]
  };
  return map;
}

@end
