/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLVerbatmAppPage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppPage (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVerbatmAppImage;
@class GTLVerbatmAppVideo;

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppPage
//

@interface GTLVerbatmAppPage : GTLObject
@property (nonatomic, retain) NSArray *images;  // of GTLVerbatmAppImage
@property (nonatomic, retain) NSNumber *key;  // longLongValue
@property (nonatomic, copy) NSString *text;
@property (nonatomic, retain) NSArray *videos;  // of GTLVerbatmAppVideo
@end
