//
//  ImageVideoUpload.h
//  Verbatm
//
//  Takes a piece of media (image or video data) and an upload uri
// generated by the server and uploads the data to the uri
//

#import <Foundation/Foundation.h>
#import <AVFoundation/AVFoundation.h>

#import <PromiseKit/PromiseKit.h>


typedef void(^MediaUploadCompletionBlock)(NSError* error, NSString* responseURL);

@interface MediaUploader : NSObject

@property (nonatomic, strong) NSProgress* mediaUploadProgress;

-(AnyPromise*) uploadVideoWithUrl:(NSURL*)videoURL andUri:(NSString*)uri;

-(AnyPromise*) uploadImageWithData:(NSData*)imageData andUri:(NSString*)uri;

@end
