//
//  ImageVideoUpload.h
//  Verbatm
//
//  Takes a piece of media (image or video data) and an upload uri
// generated by the server and uploads the data to the uri
//

#import <Foundation/Foundation.h>
#import <AVFoundation/AVFoundation.h>
#import "ASIFormDataRequest.h"

@interface MediaUploader : NSObject

@property (nonatomic, strong) ASIFormDataRequest *formData;
@property (nonatomic, assign) float progress;

-(instancetype) initWithImage:(UIImage*)img andUri: (NSString*)uri;

-(instancetype) initWithVideoData: (NSData*)videoData  andUri: (NSString*)uri;

-(void) startUpload;

@end
