/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLVerbatmAppIdentifierListWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   verbatmApp/v1
// Description:
//   This is an API
// Classes:
//   GTLVerbatmAppIdentifierListWrapper (0 custom class methods, 1 custom properties)

#import "GTLVerbatmAppIdentifierListWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLVerbatmAppIdentifierListWrapper
//

@implementation GTLVerbatmAppIdentifierListWrapper
@dynamic identifiers;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"identifiers" : [NSNumber class]
  };
  return map;
}

@end
